# Overrides system.build.VMA to pass copyChannel = false to make-disk-image.nix.
#
# By default, make-disk-image.nix includes the entire nixpkgs source tree in every
# disk image (copyChannel = true). Building it runs cp -prd on thousands of small
# files between two store paths on the same XFS filesystem, which modern coreutils
# (≥9.5 copy_file_range) tries to reflink — failing with ENOSPC when the refcount
# B-tree is exhausted, even though df shows free space.
#
# For flakes-only hosts with nix.channel.enable = false, embedding a channel source
# is pointless. This module reconstructs the VMA derivation call identically to
# proxmox-image.nix but with copyChannel = false.
#
# Import this inside image.modules.proxmox in each host's proxmox.nix.
# upstreamHash below pins the sha256 of nixos/modules/virtualisation/proxmox-image.nix at the
# nixpkgs rev in flake.lock. If that file changes, the image build fails with a re-sync prompt
# instead of silently drifting. Update: diff the new upstream, port changes here, bump the hash.
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.proxmox;
  cfgLine = name: value: "${name}: ${toString value}\n";
  virtio0Storage = builtins.head (builtins.split ":" cfg.qemuConf.virtio0);
  cfgFile = fileName: properties:
    pkgs.writeTextDir fileName ''
      # generated by NixOS
      ${lib.concatStrings (lib.mapAttrsToList cfgLine properties)}
      #qmdump#map:virtio0:drive-virtio0:${virtio0Storage}:raw:
    '';
  vma =
    (pkgs.qemu_kvm.override {
      alsaSupport = false;
      pulseSupport = false;
      sdlSupport = false;
      jackSupport = false;
      gtkSupport = false;
      vncSupport = false;
      smartcardSupport = false;
      spiceSupport = false;
      ncursesSupport = false;
      libiscsiSupport = false;
      tpmSupport = false;
      numaSupport = false;
      seccompSupport = false;
      guestAgentSupport = false;
    }).overrideAttrs
    (super: {
      version = "9.0.0";
      src = pkgs.fetchurl {
        url = "https://download.qemu.org/qemu-9.0.0.tar.xz";
        hash = "sha256-MnCKxmww2MiSYz6paMdxwcdtWX1w3erSGg0izPOG2mk=";
      };
      patches = [
        "${pkgs.fetchFromGitHub {
          owner = "proxmox";
          repo = "pve-qemu";
          rev = "14afbdd55f04d250bd679ca1ad55d3f47cd9d4c8";
          hash = "sha256-lSJQA5SHIHfxJvMLIID2drv2H43crTPMNIlIT37w9Nc=";
        }}/debian/patches/pve/0027-PVE-Backup-add-vma-backup-format-code.patch"
      ];
      buildInputs = super.buildInputs ++ [pkgs.libuuid];
      nativeBuildInputs = super.nativeBuildInputs ++ [pkgs.perl];
    });
  postVM = ''
    ${vma}/bin/vma create "${config.image.baseName}.vma" \
      -c ${
      cfgFile "qemu-server.conf" (
        # additionalSpace, bootSize, diskSize are build params consumed by
        # make-disk-image; they don't belong in the runtime VM conf and cause
        # "unable to parse config" warnings when Proxmox reads the VMA.
        builtins.removeAttrs (cfg.qemuConf // cfg.qemuExtraConf) [
          "additionalSpace"
          "bootSize"
          "diskSize"
        ]
      )
    }/qemu-server.conf drive-virtio0=$diskImage
    rm $diskImage
    ${pkgs.zstd}/bin/zstd "${config.image.baseName}.vma"
    mv "${config.image.fileName}" $out/

    mkdir -p $out/nix-support
    echo "file vma $out/${config.image.fileName}" > $out/nix-support/hydra-build-products
  '';
  pveBaseConfigs = {
    name = config.image.baseName;
    baseName = config.image.baseName;
    inherit (cfg) partitionTableType;
    inherit (cfg.qemuConf) additionalSpace bootSize;
    inherit (config.virtualisation) diskSize;
    format = "raw";
    inherit config lib pkgs;
  };
  upstreamModule = "${pkgs.path}/nixos/modules/virtualisation/proxmox-image.nix";
  upstreamHash = "f4ae5f565099cb2bc8733d9b4ab5112e88c6e38387706f90192cff118acebc8f";
in {
  system.build.VMA = lib.mkForce (
    assert lib.assertMsg
    (builtins.hashFile "sha256" upstreamModule == upstreamHash)
    "modules/proxmox-no-channel.nix duplicates ${upstreamModule}, which changed upstream. Diff the new version, port any relevant changes here, then update upstreamHash.";
      import "${pkgs.path}/nixos/lib/make-disk-image.nix" (
        pveBaseConfigs
        // {
          inherit postVM;
          copyChannel = false;
        }
      )
  );
}
