# Overrides system.build.VMA to pass copyChannel = false to make-disk-image.nix.
#
# By default, make-disk-image.nix includes the entire nixpkgs source tree in every
# disk image (copyChannel = true). Building it runs cp -prd on thousands of small
# files between two store paths on the same XFS filesystem, which modern coreutils
# (≥9.5 copy_file_range) tries to reflink — failing with ENOSPC when the refcount
# B-tree is exhausted, even though df shows free space.
#
# For flakes-only hosts with nix.channel.enable = false, embedding a channel source
# is pointless. This module reconstructs the VMA derivation call identically to
# proxmox-image.nix but with copyChannel = false.
#
# Import this inside image.modules.proxmox in each host's proxmox.nix.
# Needs to be kept in sync with proxmox-image.nix when the nixpkgs vma version/hash changes.
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.proxmox;
  cfgLine = name: value: "${name}: ${toString value}\n";
  virtio0Storage = builtins.head (builtins.split ":" cfg.qemuConf.virtio0);
  cfgFile = fileName: properties:
    pkgs.writeTextDir fileName ''
      # generated by NixOS
      ${lib.concatStrings (lib.mapAttrsToList cfgLine properties)}
      #qmdump#map:virtio0:drive-virtio0:${virtio0Storage}:raw:
    '';
  vma =
    (pkgs.qemu_kvm.override {
      alsaSupport = false;
      pulseSupport = false;
      sdlSupport = false;
      jackSupport = false;
      gtkSupport = false;
      vncSupport = false;
      smartcardSupport = false;
      spiceSupport = false;
      ncursesSupport = false;
      libiscsiSupport = false;
      tpmSupport = false;
      numaSupport = false;
      seccompSupport = false;
      guestAgentSupport = false;
    }).overrideAttrs
    (super: {
      version = "9.0.0";
      src = pkgs.fetchurl {
        url = "https://download.qemu.org/qemu-9.0.0.tar.xz";
        hash = "sha256-MnCKxmww2MiSYz6paMdxwcdtWX1w3erSGg0izPOG2mk=";
      };
      patches = [
        "${pkgs.fetchFromGitHub {
          owner = "proxmox";
          repo = "pve-qemu";
          rev = "14afbdd55f04d250bd679ca1ad55d3f47cd9d4c8";
          hash = "sha256-lSJQA5SHIHfxJvMLIID2drv2H43crTPMNIlIT37w9Nc=";
        }}/debian/patches/pve/0027-PVE-Backup-add-vma-backup-format-code.patch"
      ];
      buildInputs = super.buildInputs ++ [pkgs.libuuid];
      nativeBuildInputs = super.nativeBuildInputs ++ [pkgs.perl];
    });
  postVM = ''
    ${vma}/bin/vma create "${config.image.baseName}.vma" \
      -c ${
      cfgFile "qemu-server.conf" (cfg.qemuConf // cfg.qemuExtraConf)
    }/qemu-server.conf drive-virtio0=$diskImage
    rm $diskImage
    ${pkgs.zstd}/bin/zstd "${config.image.baseName}.vma"
    mv "${config.image.fileName}" $out/

    mkdir -p $out/nix-support
    echo "file vma $out/${config.image.fileName}" > $out/nix-support/hydra-build-products
  '';
  pveBaseConfigs = {
    name = config.image.baseName;
    baseName = config.image.baseName;
    inherit (cfg) partitionTableType;
    inherit (cfg.qemuConf) additionalSpace bootSize;
    inherit (config.virtualisation) diskSize;
    format = "raw";
    inherit config lib pkgs;
  };
in {
  system.build.VMA = lib.mkForce (
    import "${pkgs.path}/nixos/lib/make-disk-image.nix" (
      pveBaseConfigs
      // {
        inherit postVM;
        copyChannel = false;
      }
    )
  );
}
