# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      # availableKernelModules = ["virtio_pci" "virtio_blk" "virtio_scsi" "sd_mod" "ext4"];
      availableKernelModules = ["virtio_pci" "virtio_blk" "virtio_scsi" "sd_mod" "ext4" "ata_piix" "uhci_hcd"];
      kernelModules = [];
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
    loader = {
      timeout = lib.mkForce 5;
      grub = {
        enable = true;
        # device = "/dev/sda";
        devices = ["nodev"];
      };
    };
    growPartition = lib.mkDefault true;
    # loader.grub.device = lib.mkDefault "/dev/vda";
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 2048;
    }
  ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
      neededForBoot = true;
      autoResize = true;
    };
    # NOTE: /nix will be moved to a separate 50G disk post-deploy.
    # After attaching a second virtio disk in Proxmox and moving the nix store, add:
    #   fileSystems."/nix" = {
    #     device = "/dev/disk/by-label/nix-store";
    #     fsType = "xfs";
    #     options = ["noatime"];
    #     neededForBoot = true;
    #   };
  };

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
