name: nix-flake-check
on:
  pull_request:
  push:
    branches: [master]

jobs:
  check:
    name: Run nix flake check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: nix flake check
        run: nix flake check --all-systems --override-input priv ./priv 
